### PR TITLE
my wallpaper changes

### PR DESCRIPTION
**Pull request by 466gaming**
- made my wallpapers 1080p
- linked myself
- changed "466gaming" to "466"

### CODE REVIEW

**Comment by spotlightishere** [comment]
lol nice

**Comment by Abequinn** [comment]
isn't 1080p 1920x1080

**Comment by 466gaming** [comment]
yes, the website doesn't feel like updating

**Comment by spotlightishere** [comment]
We actually have to manually pull website changes and it would appear someone didn't do that. Let me go do so.

**Comment by spotlightishere** [comment]
enjoy 🎉

**Pull request merged**
