### PR TITLE
Updated the donator name

### PR DESCRIPTION
**Pull request by Mkwiiripper**
Hi yes im mkwii ripper aka Fun4TubeGr so you frogot to upadate the WrostDolphinUser to the current name wich is BlueHairedBoy

### CODE REVIEW

**Comment by KcrPL** [comment]
Not sure what to do about it...

**Comment by Mkwiiripper** [comment]
But why to use an outdated name?

**Comment by KcrPL** [comment]
Obviously you aren't WrostDolphinUser or BlueHairedBoy. If that guy would like to update his nickname - he would contact us.

**Comment by Artuto** [comment]
Actually, BlueHairedBoy is a donator

**Comment by Mkwiiripper** [comment]
Ok now

**Comment by KcrPL** [comment]
I got a proof from Mkwiiripper:

Proof

**Pull request merged**
