### PR TITLE
Better quality audios.

### PR DESCRIPTION
**Pull request by gustarrini**
Comparison: https://drive.google.com/uc?id=1eqJgQpfYvzPW_H4HHGgw-5ZKjTQ-ao6w

### CODE REVIEW

**Comment by larsenv** [comment]
Thanks.

Could you please elaborate more on how this is higher quality? I can’t hear the difference especially when you didn’t make the comparisons side by side.

I used Sharpii to rip the Channel banner sounds.

**Comment by KcrPL** [comment]
~~I can't really see the difference too~~

And I guess if you got it using Sharpii then it's then it's the best quality that you can get.

**Comment by gustarrini** [comment]
I placed an extra EQing between the audios so it looks sharper.

by making that you can also notice more percussions that you couldn't hear on the original track (one example is wiimenuroom.wav, where you can slightly hear some birds or notes at the middle).

**Comment by larsenv** [comment]
OK cool, will accept the PR.

**Pull request merged**
