### PR TITLE
CSS refactoring

### PR DESCRIPTION
**Pull request by suhankins**
* fix horizontal scrollbar always being on the screen
* refactor style.css
* greatly simplify a lot of classes (i.e. remove white-text because it's functionally exactly the same as .light but more confusing)
* fix 2 codefactor issues in card-title styling

Visually everything should look exactly the same as it does now in both dark and light modes.

I actually just wanted to limit width of the page so text doesn't go from one side of the screen to another on wide displays, but I got quickly distracted trying to make sense of current CSS.

### CODE REVIEW

**Review by Nightcaat — APPROVED** [review]
Good refactor, you love to see it

**Comment by larsenv** [comment]
Thank you much.

**Comment by larsenv** [comment]
I just tried this out and the text color is broken if your computer's set to dark mode, it would be nice if you could fix it.

**Comment by suhankins** [comment]
> I just tried this out and the text color is broken if your computer's set to dark mode, it would be nice if you could fix it.

That's odd, last time I checked colors looked fine in both dark and light mode. I will look into it.

**Comment by suhankins** [comment]
@larsenv could you provide screenshots where is text color wrong? Testing my changes now, it looks perfectly fine.
image
image

**Comment by larsenv** [comment]
For me the text looked blue.

**Comment by larsenv** [comment]
I would readd your change but GitHub says it can't be automatically merged. I hate Git. Fucking hard to work with.

**Comment by larsenv** [comment]
OK I just looked, the text on footer is messed up, it's blue when it should be white.

**Comment by Nightcaat** [comment]
I built from the latest commit and things look fine now

**Pull request merged**
