### PR TITLE
Never say Never!!!!!!

### PR DESCRIPTION
**Pull request by wiilover**
Removed "We are not planning to bring this service back." Becuse of wii no ma development

### CODE REVIEW

**Comment by urmum-69** [comment]
Are you trolling us here?

**Comment by wiilover** [comment]
@urmum-69 what??

**Comment by 2secslater** [comment]
We didn't say "never", just there are no plans currently.

**Comment by wiilover** [comment]
Yea but wii no ma development has started

**Comment by urmum-69** [comment]
nothing has started.

**Comment by larsenv** [comment]
Sorry, but I can't take anyone with the name "wiilover" seriously.

**Comment by urmum-69** [comment]
With an account made... 15 minutes ago

**Comment by wiilover** [comment]
@urmum-69 then look at this video (is not mine)

**Comment by larsenv** [comment]
What video?

**Comment by wiilover** [comment]
@larsenv ops i corrected now btw you can't guess who im

**Comment by urmum-69** [comment]
by chance, "danny"?

**Comment by larsenv** [comment]
Danny sucks

**Comment by wiilover** [comment]
@larsenv ok you watched that video or i did somthing wrong again

**Comment by 2secslater** [comment]
> ok you watched that video or i did somthing wrong again

You are clearly wrong.

**Comment by wiilover** [comment]
Why im wrong?

**Pull request closed without merging**
