### PR TITLE
Create Everybody Votes Channel page.

### PR DESCRIPTION
**Pull request by gustarrini**
feel free to change anything from the channel's desc. as i didn't had any idea on what to write.

### CODE REVIEW

**Comment by KcrPL** [comment]
Sorry but we will make that page when it will be released.
But thanks for your work :)

**Comment by gustarrini** [comment]
np!

**Comment by larsenv** [comment]
I disagree with KcrPL, this avoids the hassle of me creating a page. Thanks.

**Comment by KcrPL** [comment]
Oh, then I'm sorry for closing that PR.

**Pull request merged**
